In [1]:
import pandas as pd
import numpy as np
data = pd.read_csv("data.csv")
data[data==' ']=np.nan
data=data.dropna()
data.head(5)
data_E=data.iloc[0:50,:]
data_T=data.iloc[50::,:]
stress=np.int8(data_E.iloc[:,31])
tired=np.int8(data_E.iloc[:,32])
st=np.int8(data_E.iloc[:,31:33])
choice3=np.int8(data_E.iloc[:,37])
choice4=np.int8(data_E.iloc[:,38])
tend=np.int8(choice3)+np.int8(choice4)
choice3=np.int8(data_T.iloc[:,37])
choice4=np.int8(data_T.iloc[:,38])
tend_t=np.int8(choice3)+np.int8(choice4)
choice3=data.iloc[:,37]
choice4=data.iloc[:,38]
tend_all=np.int8(choice3)+np.int8(choice4)
payoff=np.float32(data_E.iloc[:,33])
payoff_t=np.float32(data_T.iloc[:,33])
pay_off_all=np.float32(data.iloc[:,33])

/afs/inf.ed.ac.uk/user/s18/s1883226/miniconda3/envs/mlp/lib/python3.6/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


In [2]:
from g_factors2 import model_update

In [3]:
np.random.randint(0,50,10)

array([37,  3, 22,  6, 11,  9, 43, 21, 33, 38])

In [7]:
for j in range (0,200):
    for i in range (0,5):
        k=np.random.randint(0,50,20)
        model_update(data.iloc[k,:])

In [ ]:
a=[]
np.array(a).any()


In [18]:
from g_factors3 import gen_f
from sklearn.model_selection import train_test_split
from scipy.stats import burr
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from distribut import best_fit_distribution
import numpy as np
f1,f2,f3,f4,f5,f6,f7,f8,f9=gen_f(data_E,update=False)
X_train, X_test, y_train, y_test = train_test_split(np.vstack((f1,f2,f3,f4,f5)).T, tend, test_size=0.2, random_state=0)
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
print(mean_absolute_error(tend, lin_reg.predict(np.vstack((f1,f2,f3,f4,f5)).T)))
r2_score(tend, lin_reg.predict(np.vstack((f1,f2,f3,f4,f5)).T))

3.283011302223879


0.44540355042330493

In [12]:
np.load('m4.npy')

array([0., 1.])

In [16]:
tend_t

array([13, 22, 22, 11, 13, 17, 22, 14, 20, 12, 21, 13, 25, 13, 23,  4, 19,
        9, 22, 15, 14, 17, 24, 14,  8, 16, 21, 29,  5, 16,  8, 32, 24, 13,
       27, 21, 20, 17, 14, 16, 10, 17, 21, 12, 22, 16, 17, 17, 31, 16, 30,
       16, 18, 23, 30, 15], dtype=int8)

In [19]:
f1,f2,f3,f4,f5,f6,f7,f8,f9=gen_f(data_T,update=False)
print(mean_absolute_error(tend_t, lin_reg.predict(np.vstack((f1,f2,f3,f4,f5)).T)))
r2_score(tend_t, lin_reg.predict(np.vstack((f1,f2,f3,f4,f5)).T))

4.375619886955413


0.10688258185400257

In [11]:
f1,f2,f3,f4,f5=gen_f(data,update=False)
print(mean_absolute_error(tend_all, lin_reg.predict(np.vstack((f1,f2,f3,f4,f5)).T)))
r2_score(tend_all, lin_reg.predict(np.vstack((f1,f2,f3,f4,f5)).T))

3.867456693549374


0.3004706631359937

In [13]:
train=np.hstack((data_E.iloc[:,21:33],np.array(data_E.iloc[:,34]).reshape(50,1),np.array(data_E.iloc[:,39]).reshape(50,1),data_E.iloc[:,1:11]))
test=np.hstack((data_T.iloc[:,21:33],np.array(data_T.iloc[:,34]).reshape(56,1),np.array(data_T.iloc[:,39]).reshape(56,1),data_T.iloc[:,1:11]))
test_all=np.hstack((data.iloc[:,21:33],np.array(data.iloc[:,34]).reshape(106,1),np.array(data.iloc[:,39]).reshape(106,1),data.iloc[:,1:11]))

In [14]:
lin_reg = LinearRegression()
lin_reg.fit(train, tend)
print(mean_absolute_error(tend_t, lin_reg.predict(test)))
r2_score(tend_t, lin_reg.predict(test))

5.37554521431295


-0.14458755727255346

In [17]:
lin_reg = LinearRegression()
lin_reg.fit(test_all, tend_all)
print(mean_absolute_error(tend_all, lin_reg.predict(test_all)))
r2_score(tend_all, lin_reg.predict(test_all))

3.3377707382791746


0.4903967390210715

In [13]:
from g_factors3 import gen_f
from sklearn.model_selection import train_test_split
from scipy.stats import burr
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from distribut import best_fit_distribution
import numpy as np
f1,f2,f3,f4,f5,f6,f7,f8,f9=gen_f(data_E,update=False)
X_train, X_test, y_train, y_test = train_test_split(np.vstack((f6,f7,f8,f9)).T, payoff, test_size=0.2, random_state=0)
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
f1,f2,f3,f4,f5,f6,f7,f8,f9=gen_f(data_T,update=False)
print(mean_absolute_error(payoff_t, lin_reg.predict(np.vstack((f6,f7,f8,f9)).T)))
r2_score(payoff_t, lin_reg.predict(np.vstack((f6,f7,f8,f9)).T))

71.47740719816468


0.5691396371709612

In [3]:
test=np.hstack((data_E.iloc[:,21:33],np.array(data_E.iloc[:,34]).reshape(50,1),np.array(data_E.iloc[:,39]).reshape(50,1),data_E.iloc[:,1:11],data_E.iloc[:,37:38],data_E.iloc[:,11:21]))
test_t=np.hstack((data_T.iloc[:,21:33],np.array(data_T.iloc[:,34]).reshape(56,1),np.array(data_T.iloc[:,39]).reshape(56,1),data_T.iloc[:,1:11],data_T.iloc[:,37:38],data_T.iloc[:,11:21]))

In [4]:
X_train, X_test, y_train, y_test = train_test_split(test, payoff, test_size=0.2, random_state=0)
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
print(mean_absolute_error(payoff_t, lin_reg.predict(test_t)))
r2_score(payoff_t, lin_reg.predict(test_t))

130.8581751190339


-0.46472032282402065

In [12]:
from g_factors3 import model_update
for j in range (0,200):
    k=np.random.randint(0,50,20)
    model_update(data.iloc[k,:])